version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3002:3002"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend/keyguardian_app:/app
  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: keyguardian
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: