name: lambda_github_action_test_deploy deploy 
on:
  push:
    paths:
      - 'keyguardian-api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: get-caller-identity is allowed to run on role.
        run: aws sts get-caller-identity

      - name: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          pip3 install awscli

      - name: package lambda
        run: |
          cd keyguardian-api
          mv get_key_status.js index.js
          zip -r ../package_get.zip index.js
          mv index.js get_key_status.js
          mv post_key_update.js index.js
          zip -r ../package_post.zip index.js
          mv index.js post_key_update.js
          cd ..

      - name: lambda update
        run: |
          aws lambda update-function-code --function-name get_key_status --zip-file fileb://package_get.zip --publish
          aws lambda update-function-code --function-name post_key_update --zip-file fileb://package_post.zip --publish